name: reading_promotion_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  cupertino_icons: ^1.0.6
  google_sign_in:
  device_preview:
  http: ^1.2.0
  simple_barcode_scanner: ^0.0.8
  awesome_dialog: ^3.2.0
  flutter_riverpod:
  flutter_hooks:
  riverpod_annotation:
  google_fonts:
  flutter_slidable:
  json_annotation:
  liveroom:
  percent_indicator:
  go_router:
  pixel_color_image:
  web_socket_channel:
  envied:
  shared_preferences:
  firebase_core: ^2.25.4
  cloud_firestore:
  firebase_storage: ^11.6.5

dev_dependencies:
  freezed:
  riverpod_generator:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

flutter:
  assets:
   - assets/images/
   - assets/images/parts/
   - assets/parts_adjustment.json
  uses-material-design: true
