// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0YDd0RyX9TUP5XlW0BFbkrzEHkkoBvLQ',
    appId: '1:955259076235:web:cade7cafaa0aceca181e8e',
    messagingSenderId: '955259076235',
    projectId: 'coriander-app-f5b22',
    authDomain: 'coriander-app-f5b22.firebaseapp.com',
    storageBucket: 'coriander-app-f5b22.appspot.com',
    measurementId: 'G-LLR2QLZHKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTP3Ohsgd3GHEUkzbs4dkdCKZcP3O-Cg8',
    appId: '1:955259076235:android:9cb4d02b0fbc8282181e8e',
    messagingSenderId: '955259076235',
    projectId: 'coriander-app-f5b22',
    storageBucket: 'coriander-app-f5b22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVwAUlr5C2Gu5kv9BNbIw3UcyihVgLQWM',
    appId: '1:955259076235:ios:37248f03b7e01b84181e8e',
    messagingSenderId: '955259076235',
    projectId: 'coriander-app-f5b22',
    storageBucket: 'coriander-app-f5b22.appspot.com',
    iosBundleId: 'com.example.readingPromotionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVwAUlr5C2Gu5kv9BNbIw3UcyihVgLQWM',
    appId: '1:955259076235:ios:b3673fce93c56542181e8e',
    messagingSenderId: '955259076235',
    projectId: 'coriander-app-f5b22',
    storageBucket: 'coriander-app-f5b22.appspot.com',
    iosBundleId: 'com.example.readingPromotionApp.RunnerTests',
  );
}
